import type { Metadata } from "next";
import { Geist, Geist_Mono , Lexend , Anton } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["vietnamese"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="box-border m-0 border-0 block">
      <body
        className={`${lexend.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-background flex min-h-svh flex-col w-full">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
